#!/usr/bin/env python3
"""
Create Evidence Snapshot - Sovereign Sanctuary Elite

Create cryptographically sealed evidence snapshot for external verification.
This is the EXTERNAL-FACING proof artifact.

Version: 2.0.0
Author: Manus AI for Architect

SNAPSHOT CONTENTS:
- Selected evidence files
- MANIFEST.json with hashes
- VERIFY.sh for one-command verification
- README.md for external parties
"""

import json
import hashlib
import shutil
import sys
import argparse
from pathlib import Path
from datetime import datetime, timezone
from typing import List, Dict, Any

# ═══════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════

OUTPUT_DIR = Path("EVIDENCE_SNAPSHOTS")
LEDGER_PATH = Path("evidence/ledger.jsonl")

# Default files to include in snapshot
DEFAULT_SNAPSHOT_FILES = [
    "evidence/ledger.jsonl",
    "evidence/SITREP.md",
    "runtime/state.json",
    "README.md",
]

# ═══════════════════════════════════════════════════════════════════
# CORE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════

def sha256_file(path: Path) -> str:
    """Calculate SHA-256 hash of a file"""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(8192), b""):
            h.update(block)
    return h.hexdigest()


def sha256_string(data: str) -> str:
    """Calculate SHA-256 hash of a string"""
    return hashlib.sha256(data.encode("utf-8")).hexdigest()


def create_verify_script(snapshot_dir: Path) -> None:
    """Create one-command verification script"""
    script = '''#!/bin/bash
# VERIFY.sh - One-command snapshot verification
# Generated by Sovereign Sanctuary Elite

set -e

echo "=================================="
echo "EVIDENCE SNAPSHOT VERIFICATION"
echo "=================================="

MANIFEST="MANIFEST.json"

if [ ! -f "$MANIFEST" ]; then
    echo "❌ MANIFEST.json not found"
    exit 1
fi

echo "Verifying files..."

# Extract file paths and hashes from manifest
python3 -c "
import json, hashlib, sys
from pathlib import Path

def sha256(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(8192), b''):
            h.update(b)
    return h.hexdigest()

m = json.loads(Path('MANIFEST.json').read_text())
ok = True
for f in m['files']:
    p = Path(f['name'])
    if not p.exists():
        print(f'❌ MISSING: {f[\"name\"]}')
        ok = False
    elif sha256(p) != f['sha256']:
        print(f'❌ HASH MISMATCH: {f[\"name\"]}')
        ok = False
    else:
        print(f'✅ VERIFIED: {f[\"name\"]}')

sys.exit(0 if ok else 1)
"

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ SNAPSHOT VERIFIED - ALL FILES INTACT"
    exit 0
else
    echo ""
    echo "❌ VERIFICATION FAILED"
    exit 1
fi
'''
    
    script_path = snapshot_dir / "VERIFY.sh"
    script_path.write_text(script, encoding="utf-8")
    script_path.chmod(0o755)


def create_readme(snapshot_dir: Path, snapshot_id: str, manifest_hash: str) -> None:
    """Create README for external parties"""
    readme = f'''# Evidence Snapshot: {snapshot_id}

## Quick Verification

Run this command to verify all files:

```bash
./VERIFY.sh
```

Or manually verify the manifest hash:

```bash
sha256sum MANIFEST.json
# Expected: {manifest_hash}
```

## What This Proves

This snapshot provides cryptographic proof that the included files existed
in their current form at the time of snapshot creation.

## Contents

See MANIFEST.json for the complete list of files and their SHA-256 hashes.

## Verification Steps

1. Check MANIFEST.json hash matches the expected value
2. For each file in manifest, verify SHA-256 hash matches
3. If all hashes match, the snapshot is verified

## Contact

Generated by Sovereign Sanctuary Elite
Snapshot ID: {snapshot_id}
'''
    
    readme_path = snapshot_dir / "README.md"
    readme_path.write_text(readme, encoding="utf-8")


def log_snapshot(snapshot_id: str, manifest_hash: str, file_count: int) -> None:
    """Log the snapshot creation to the ledger"""
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    entry = {
        "event": "EVIDENCE_SNAPSHOT_CREATED",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "snapshot_id": snapshot_id,
        "manifest_hash": manifest_hash,
        "file_count": file_count
    }
    
    with LEDGER_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")


# ═══════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════

def main() -> int:
    """
    Create an evidence snapshot.
    
    Returns:
        0 on success, 1 on failure
    """
    parser = argparse.ArgumentParser(
        description="Create cryptographically sealed evidence snapshot"
    )
    parser.add_argument(
        "--files",
        nargs="+",
        default=DEFAULT_SNAPSHOT_FILES,
        help="Files to include in snapshot"
    )
    parser.add_argument(
        "--label",
        default="",
        help="Optional label for the snapshot"
    )
    
    args = parser.parse_args()
    
    print("\n" + "=" * 60)
    print("SOVEREIGN SANCTUARY ELITE - CREATE EVIDENCE SNAPSHOT")
    print("=" * 60)
    
    # Generate snapshot ID
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    label_suffix = f"_{args.label}" if args.label else ""
    snapshot_id = f"SNAPSHOT_{stamp}{label_suffix}"
    snapshot_dir = OUTPUT_DIR / snapshot_id
    
    print(f"Snapshot ID: {snapshot_id}")
    print(f"Output Dir: {snapshot_dir}")
    print("-" * 60)
    
    # Create snapshot directory
    snapshot_dir.mkdir(parents=True)
    
    # Copy files and build manifest
    files: List[Dict[str, Any]] = []
    
    for file_path_str in args.files:
        source = Path(file_path_str)
        
        if not source.exists():
            print(f"  ⏭️  Skipped (not found): {file_path_str}")
            continue
        
        # Use just the filename in snapshot
        dest_name = source.name
        dest = snapshot_dir / dest_name
        
        shutil.copy2(source, dest)
        
        file_hash = sha256_file(dest)
        files.append({
            "name": dest_name,
            "original_path": file_path_str,
            "sha256": file_hash,
            "size": dest.stat().st_size
        })
        print(f"  ✅ Included: {file_path_str} → {dest_name}")
    
    if not files:
        print("\n❌ No files included in snapshot")
        shutil.rmtree(snapshot_dir)
        return 1
    
    # Create manifest
    manifest = {
        "snapshot_id": snapshot_id,
        "creation_timestamp": datetime.now(timezone.utc).isoformat(),
        "hash_algorithm": "SHA-256",
        "file_count": len(files),
        "files": files
    }
    
    manifest_path = snapshot_dir / "MANIFEST.json"
    manifest_json = json.dumps(manifest, indent=2, sort_keys=True)
    manifest_path.write_text(manifest_json, encoding="utf-8")
    
    manifest_hash = sha256_string(manifest_json)
    
    # Create verification script
    create_verify_script(snapshot_dir)
    print("  ✅ Created: VERIFY.sh")
    
    # Create README
    create_readme(snapshot_dir, snapshot_id, manifest_hash)
    print("  ✅ Created: README.md")
    
    # Log to ledger
    log_snapshot(snapshot_id, manifest_hash, len(files))
    
    # Print summary
    print("-" * 60)
    print("✅ EVIDENCE SNAPSHOT CREATED SUCCESSFULLY")
    print(f"   Snapshot ID:   {snapshot_id}")
    print(f"   Files:         {len(files)}")
    print(f"   Manifest Hash: {manifest_hash}")
    print(f"   Location:      {snapshot_dir.absolute()}")
    print("\nTo verify: cd {snapshot_dir} && ./VERIFY.sh")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
